### PR TITLE
build: support cross compiling

### LINKED ISSUE #78: flex 2.6.1 does not cross compile
As of 53e3088, flex runs stage1flex to bootstrap itself. Unfortunately, this fails when cross compiling, as stage1flex is built for the target architecture (not for the host machine).

I'm unsure how to fix this as my knowledge of GNU autotools is limited; but http://lists.gnu.org/archive/html/automake/2008-12/msg00016.html seems to suggest a way to make this work.

### PR DESCRIPTION
**Pull request by hobbitalastair**
Check for cross compiling. If cross compiling, build stage1flex using a custom link command.
We also override LDADD since that adds the replacement implementations that are cross compiled, and instead always use the replacement library implementations.

We don't use BUILD_OBJEXT and BUILD_EXEEXT since it seems that automake does not support these.

Fixes #78.

Signed-off-by: Alastair Hughes <hobbitalastair@gmail.com>

### CODE REVIEW

**Comment by rossburton** [comment]
With this patch to get a non-cross build working I need to set stage1flex_LINK = $(LINK) in the non-cross case, otherwise it tries using stage1flex_LINK which isn't defined.  I guess I can moan at libtool for this, but apart from that this appears to work for me.

**Comment by hobbitalastair** [comment]
@rossburton thanks! - I've pushed an updated patch that should fix that. It seems to build fine locally now.

**Comment by Explorer09** [comment]
I would like to take some time to look at this and test it.
But, I hope you could also look at issue #73 and address it (have a build-time m4 path) in your cross-compile patch.

**Comment by hobbitalastair** [comment]
@Explorer09 I'd rather keep that in a separate patch since cross-compiling does not require it.

**Comment by Explorer09** [comment]
The BUILD_EXEEXT and BUILD_OBJEXT parts of AX_PROG_CC_FOR_BUILD is currently broken.
AX_PROG_CC_FOR_BUILD depend on AC_EXEEXT to determine the extensions, but the recent autoconf (2.69 in my testing) makes AC_EXEEXT expands to empty code so that BUILD_OBJEXT et al. will not be detected correctly. (Autoconf has internal _AC_COMPILER_EXEEXT macro, but it's supposed to be expanded once, hence it cannot substitute for AC_EXEEXT directly for AX_PROG_CC_FOR_BUILD use case.)
**This is a bug and should be reported.**

**Comment by westes** [comment]
As per github, This branch has conflicts that must be resolved". Please resolve them and push the updates.Thanks!

**Comment by westes** [comment]
Much thanks for the update. It's in the queue to review.

**Comment by westes** [comment]
I had to remove the listing of lib/reallocarray.c since that file is no longer in the git tree.

**Comment by westes** [comment]
In general, I don't like listing the lib/files explicitly because it means tracking them manually. That being said, I don't see a way around that.

**Comment by westes** [comment]
I also note that ./.gitignore ignores m4/ and so I want to make sure that adding in the file in m4/ is not going to bite us. That is the right place for it, I am just concerned about the use of .gitignore above it.

**Comment by westes** [comment]
Thanks. This is on master and will be included in the next release.

**Pull request closed without merging**
