### PR TITLE
.gitignore adjustments for WIN32

### PR DESCRIPTION
**Pull request by GitMensch**
additional ignoring .obj and .exe

### CODE REVIEW

**Comment by Croydon** [comment]
@GitMensch Ping for a rebase. Seems like a low hanging fruit to merge

**Comment by GitMensch** [comment]
agreed, doing that now

**Comment by westes** [comment]
This is now on master; thanks!

**Comment by GitMensch** [comment]
please see the diff, it is not in yet, just reopen and merge (or manually add)

**Comment by GitMensch** [comment]
I think it is all fine but this line https://github.com/westes/flex/commit/0d08e372bcbd2705da102ee9678d9d55b8be8da9#diff-d3df2e75cba7371c50176ae21f74c8504b179c83eac66a9a9f0af873d23a6d4aR30

**Comment by westes** [comment]
Yup, I'll get that line removed it -- missed it when resolving the conflict.

The other files on your branch aren't a part of the .gitignore changes.

**Pull request closed without merging**
