### PR TITLE
consistent prefix 'FLEX_TOK_' of token names

### PR DESCRIPTION
**Pull request by jannick0**
Replacing #297 (unfortunately I don't know how to change commits of a PR which is why I simply opened this new one; I'll close the previous one in a second. I am still struggling with the git animal).

@westes ... here a list with potential TODOs:
- [ ] check `bison >= 3.0` in `configure` step (?) 
- [ ] amend documentation (?)

### CODE REVIEW

**Comment by westes** [comment]
You just push commits to the tip of the branch that the pr is on and github does the rest. Admittedly, you should clean up / rebase the branch so it looks the way you want it, but opening a clean pr does work.

On Wednesday, 27 December 2017,  3:37 am -0800, jannick0 <notifications@github.com> wrote:

> Replacing #297 (unfortunately I don't know how to change commits of a PR which is why I simply opened this new one; I'll close the previous one in a second. I am still struggling with the git animal).
> 
> @westes ... here a list with potential TODOs:
> - [ ] check `bison >= 3.0` in `configure` step (?) 
> - [ ] amend documentation (?)
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/westes/flex/pull/299
> 
> -- Commit Summary --
> 
>   * prefix central flex token names consistently with
> 
> -- File Changes --
> 
>     M src/parse.y (21)
>     M src/scan.l (100)
>     M src/yylex.c (48)
> 
> -- Patch Links --
> 
> https://github.com/westes/flex/pull/299.patch
> https://github.com/westes/flex/pull/299.diff
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/299

-- 
Will Estes
westes575@gmail.com

**Comment by jannick0** [comment]
Great - thanks!

**Comment by Explorer09** [comment]
May I suggest to defer this change to a major release (e.g. 2.7.0), since this bumps the Bison version requirement during bootstrap (although Bison is not required when building from a release tarball)?
Beside that, I have no comments for now, but I would like time to examine the code changes.

**Comment by westes** [comment]
At the moment, there is no explicit requirement. There is an implicit requirement that people using flex should be using at least whatever bison I happen to use to build the release tarball. That will get locked in as I automate the release process.

I don't know that this needs to wait till 2.7.0 specifically, but it's going to at least wait till 2.6.6 at a bare minimum.

Are there mainstream platforms where bison 3.X is not available?

On Thursday, 28 December 2017,  1:16 am +0000, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> May I suggest to defer this change to a major release (e.g. 2.7.0), since this bumps the Bison version requirement during bootstrap (although Bison is not required when building from a release tarball)?
> Beside that, I have no comments for now, but I would like time to examine the code changes.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/299#issuecomment-354209343

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
Looking at this, I am going to move it to 2.7.0 just because we're changing things that might surprise folk.

**Pull request closed without merging**
