### PR TITLE
Code refactoring (about allocate_array() and global arrays)

### PR DESCRIPTION
**Pull request by Explorer09**
This are not bug fixes, but are my personal attempt to refactor the code. I think these can be useful for a next feature release (2.7.0).

### CODE REVIEW

**Comment by westes** [comment]
Are you still interested in this? A number of conflicts have crept in due to time. I'm clearing out the backlog of old pr's currently, so just let me know either way.

**Comment by Explorer09** [comment]
@westes 
> Are you still interested in this? A number of conflicts have crept in due to time. I'm clearing out the backlog of old pr's currently, so just let me know either way.

I can pick a few trivial commits out for you to merge to `master`, but this branch and PR of mine is meant to be cherry-picked, not merged as a whole at once.

**Comment by Explorer09** [comment]
@westes I rebased the branch and dropped the experimental commits from this. The commits left here are what can be merged to `master` right now. If there are other refactoring works (if I have time), I might file a new PR for those.

**Comment by westes** [comment]
I'm working my way through these commits: On 525e919, I get:

gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR=\"/usr/local/share/locale\"    -g -O2 -MT flex-sym.o -MD -MP -MF .deps/flex-sym.Tpo -c -o flex-sym.o `test -f 'sym.c' || echo './'`sym.c
sym.c:209:9: error: conflicting types for ‘scinstal’; have ‘void(const char *, _Bool)’
  209 | void    scinstal (const char *str, bool sc_is_exclusive)
      |         ^~~~~~~~
In file included from sym.c:34:
flexdef.h:1044:13: note: previous declaration of ‘scinstal’ with type ‘void(const char *, int)’
 1044 | extern void scinstal(const char *, int);        /* make a start condition */
      |             ^~~~~~~~

If you'll rebase/fix that (and whatever the file conflict that has crept in, too), please, I'll continue.

**Comment by Explorer09** [comment]
> ```text
> sym.c:209:9: error: conflicting types for ‘scinstal’; have ‘void(const char *, _Bool)’
> 209 | void scinstal (const char *str, bool sc_is_exclusive)
>     |      ^~~~~~~~
> In file included from sym.c:34:
> flexdef.h:1044:13: note: previous declaration of ‘scinstal’ with type ‘void(const char *, int)’
>  1044 | extern void scinstal(const char _, int); /_ make a start condition */
>       |             ^~~~~~~~
> ```

Thanks. Fixed and rebased.

**Comment by westes** [comment]
Thanks; this is now on master.

**Pull request merged**
