### PR TITLE
Localization for Ukrainian language.

### PR DESCRIPTION
**Pull request by viktor-shepel**
**Issue:**
Flex output has no Ukrainian messages under Ukrainian locale.

**Root cause:**
Missing translation file.

**Solution:**
File with Ukrainian translation has been added to project.

ticket - https://github.com/westes/flex/issues/227

### CODE REVIEW

**Comment by Explorer09** [comment]
I think translation pull requests are better submitted to the Translation Project rather than here. As the po files of flex synchronizes with theirs periodically.

Perhaps submitting the request here would be better? https://translationproject.org/team/uk.html

**Comment by westes** [comment]
Please see [the translation project's page for translators](https://translationproject.org/html/translators.html). I have no way to evaluate the correctness of your submission and they do. Also, you need to submit the necessary disclaiming paperwork to them.

**Comment by viktor-shepel** [comment]
Thanks.
Now I've understood why we fetch *.po files from translationproject.org 
i.e. `rsync -Lrtvz  translationproject.org::tp/latest/flex/ .`

Will do it as described.

**Comment by westes** [comment]
Thanks much!

On Friday, 26 May 2017,  6:11 am -0700, Viktor <notifications@github.com> wrote:

> Thanks.
> Now I've understood why we fetch *.po files from translationproject.org 
> i.e. `rsync -Lrtvz  translationproject.org::tp/latest/flex/ .`
> 
> Will do it as described.
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/226#issuecomment-304278736

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
This was submitted through the translation project and will be included in the next release.

**Pull request closed without merging**
