### PR TITLE
Less m4

### PR DESCRIPTION
**Pull request by DemiMarie**
This changes some uses of M4 to use Flex’s skeleten file parsing machinery.

### CODE REVIEW

**Comment by DemiMarie** [comment]
I suspect that `skelout()` will *always* return `true`, but I am not certain.

**Comment by Explorer09** [comment]
Can you remove the regenerated po files from the first commit in this PR? That would make us reviewing the code easier.

**Comment by DemiMarie** [comment]
@westes would you mind reviewing this?

**Comment by westes** [comment]
Can you see about the conflicts that have ben introduced from the merging in of #489?

**Comment by DemiMarie** [comment]
> Can you see about the conflicts that have ben introduced from the merging in of #489?

Will do.  Given that we seem to be moving towards having more code in m4 (not less), I recommend that we embed a micro-m4 implementation ourselves, and have proper APIs for it.

**Comment by DemiMarie** [comment]
Update: The machinery that I was trying to move Flex to has all been removed, so this PR now only contains the changes to C source code scanning.  C++11 raw string literals and Go raw strings still need to be handled, but that will come later.

**Comment by westes** [comment]
The ultimate goal is no m4. What we need to be able to do that is to have uniformity in the code, so for now, we've got more m4 as that will be easier to replace, albeit down the road.

**Comment by Mightyjo** [comment]
Oh! Good to know. I'd been happy with m4 as an intermediate language and was heading in an m4-heavy direction. This is a good time to course correct.

How do you imagine the endgame? Would m4 be gone entirely, relegated to the skeletons, abstracted behind backend classes, other?

**Comment by westes** [comment]
Absolutely no m4 at all, anywhere.

Mind you, I have no thoughts on how we get there from here at the moment.

**Comment by DemiMarie** [comment]
> Absolutely no m4 at all, anywhere.
> 
> Mind you, I have no thoughts on how we get there from here at the moment.

The first idea that comes to mind is to use a skeleton file that is compiled to C by a Perl script.

**Pull request closed without merging**
