### PR TITLE
introduce yycalloc and apply to internal scanner structs

### PR DESCRIPTION
**Pull request by jannick0**
Use zero-initialized memory block for default initialization of struct members. If accepted

- the default initialization of struct members by 0 could be dropped.
- struct members added to the code later would be zero-initialized.

### CODE REVIEW

**Comment by Explorer09** [comment]
I wonder if this would bring performance problem for allocated data that doesn't need zero initialization, but filled in in other ways.
Look at `yy_scan_bytes` in the skeleton for an example, its `buf` is not zero-initialized, but the data is copied from `yybytes` argument.

**Comment by westes** [comment]
We're already using calloc() in some places to ensure initialization occurs with predictable behavior. I'm not convinced that performance in these cases is worth worrying about.

**Comment by Explorer09** [comment]
This patch is supposed to remove some memset() calls after yyalloc() in the skeleton, so it's already addressing performance in the first place.
I don't think using calloc() over malloc() will give a behavior any more predictable, though. This thinking won't be sufficient if you're going to address data safety.

**Comment by jannick0** [comment]
`malloc` could then be replaced by `calloc` when it comes to memory allocation of internal flex structures. This is a bit more work you are suggesting, so this needs the implementation.

**Comment by Explorer09** [comment]
@jannick0 
How about renaming all the so-called `yyalloc` to `yymalloc` or `yycalloc` to address separate needs?
I found another problem with the name `yyalloc`: Bison have been using this already. ([You can Google the word yyalloc and see its results](https://google.com/search?q=yyalloc).) It's defined as a union type.
We would better rename it as well if we are to change its behavior.

**Comment by jannick0** [comment]
- Renaming `yyalloc` to `yymalloc` and `yycalloc` would imply some additional work in `flex.skl` and `scan.l` and the documentation. Of course, `yyalloc` should be labelled as deprecated before it could be fully removed to avoid any confusion of external code calling `yyalloc` for whatever reason. 

- Compilers do not have any issues with structures / unions and functions having the same name in one single compilation entity, so this is not a real problem. If a human code reader of bison's and flex' output married ot each other became confused because of that, flex' `%option prefix=...` could help him. There are tons of examples of bison and flex pairs out there which do not cause any issue of which flex is just one fundamental one. Given flex' naming logic and features, I would stick to `yymalloc`, `yycalloc` and - for backward compatibility supposedly for over some time - a deprecated version of `yyalloc`.

**Comment by westes** [comment]
On Tuesday, 26 December 2017,  9:19 am +0000, jannick0 <notifications@github.com> wrote:

> - Renaming `yyalloc` to `yymalloc` and `yycalloc` would imply some additional work in `flex.skl` and `scan.l` and the documentation. Of course, `yyalloc` should be labelled as deprecated before it could be fully removed to avoid any confusion of external code calling `yyalloc` for whatever reason. 

Yes.

> - [...] Given flex' naming logic and features, I would stick to `yymalloc`, `yycalloc` and - for backward compatibility supposedly for over some time - a deprecated version of `yyalloc`.

Yes.

We need some sense of how widely yyalloc is used outside of flex itself. The first step in the process is to add the functions yymalloc and yycalloc and document their existence.

> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/295#issuecomment-353944072

-- 
Will Estes
westes575@gmail.com

**Comment by jannick0** [comment]
@westes @Explorer09 Updated commits:
- yycalloc introduced
- yycalloc applied to internal scanner structs only, but not to memory allocation for buffers (unneccessary and due to performance reasons).

Hope that looks better then.

**Pull request closed without merging**
