### PR TITLE
Remove integer limit macros from skeleton

### LINKED ISSUE #307: duplicate definition of INT8_MAX in Visual Studio 2015
In generated source files, [this block](https://github.com/westes/flex/blob/master/src/flexint.h#L32) is done after including `inttypes.h`, however at least on Visual Studio 2015, these are defined by `stdint.h` which is included later in the file causing redefinition warnings.

### PR DESCRIPTION
**Pull request by Explorer09**
Resolves #307.
See descriptions of both commits.

### CODE REVIEW

**Comment by mathstuf** [comment]
Thanks, this looks better indeed. One thing I might ask is that `Visual C++ is not fully C99 compliant` instead be `Older Visual C++ compilers are…`, since VS2015's toolchain is C99-compliant now (since C++11 requires it).

**Comment by Explorer09** [comment]
@mathstuf Okay. I'll correct the commits if I have time.

**Comment by westes** [comment]
Thanks; this is on master and will be included in the next release.

**Comment by Explorer09** [comment]
#329 is a regression of this pull.

**Comment by GitMensch** [comment]
> Thanks; this is on master and will be included in the next release.

Sigh, just stumbled over this ... again. So still waiting for "the next release" to land. 🥺 🙏

**Pull request closed without merging**
