### PR TITLE
Indent

### PR DESCRIPTION
**Pull request by alagoutte**

### CODE REVIEW

**Comment by Explorer09** [comment]
Would you state a reason on why you must change the space-based indent to the tab-based one?
It's a coding style problem, and changing one to another without consensus could be a bad idea.

**Comment by westes** [comment]
No, we use spaces, not tabs.

**Comment by alagoutte** [comment]
Ok i will change
4 spaces ?

**Comment by westes** [comment]
yes. Although it looks like .indent.pro needs some attention as well.

On Thursday, 22 December 2016,  4:52 am -0800, Alexis La Goutte <notifications@github.com> wrote:

> Ok i will change
> 4 spaces ?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/137#issuecomment-268793554

-- 
Will Estes
westes575@gmail.com

**Comment by westes** [comment]
Please split this up. Submit one pull request to handle trailing whitespace. Another to correct any indenting that is incorrect.

Thanks!

**Comment by alagoutte** [comment]
Ok i will close this case and i have open a first PR for whitespace https://github.com/westes/flex/pull/140

**Comment by alagoutte** [comment]
@westes Maybe switch to EditorConfig http://editorconfig.org/  ? (supported directly on major editor)

**Pull request closed without merging**
