### PR TITLE
Improved M4 quotation

### PR DESCRIPTION
**Pull request by DemiMarie**
This fixes M4 quotation of certain strings beginning with `yy` (in
section 3 of the input file only) and character literals.  The new
quotation method is also less brittle and faster.

Tests that relied on the old behavior were fixed.

Also, `yyconst` is no longer defined; use `const` (which it
unconditionally was defined to) instead.

### CODE REVIEW

**Comment by westes** [comment]
Thanks for this. It's on master and will be included in the next release of flex.

**Comment by westes** [comment]
I'm having some issues around this which I didn't see earlier. Reopening to investigate.

**Comment by westes** [comment]
This is what I'm seeing:

gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR=\"/usr/local/share/locale\" -I../intl   -g -O2 -MT stage1flex-scan.o -MD -MP -MF .deps/stage1flex-scan.Tpo -c -o stage1flex-scan.o `test -f 'scan.c' || echo './'`scan.c
scan.l: In function ‘flexscan’:
scan.l:918:33: error: expected ‘)’ before ‘;’ token
      add_action( "\tYY_BREAK]]\n" );
                                 ^
scan.l:922:5: error: expected ‘;’ before ‘}’ token
     }
     ^
scan.c: At top level:
scan.c:4337:1: error: expected identifier or ‘(’ before ‘]’ token
 ]])
 ^
scan.c:350:12: warning: ‘yy_get_next_buffer’ used but never defined
 static int yy_get_next_buffer (void );
            ^
Makefile:1077: recipe for target 'stage1flex-scan.o' failed

Pushed to https://github.com/westes/flex/tree/DemiMarie-different-quoting-pr so you can see exactly what I'm building against.

**Comment by DemiMarie** [comment]
I think it has something to do with us using different bootstrap versions of Flex: I am using a version I built from Git rather recently, while you may be using a version that predates the M4 quoting fixes I have added.  That would explain the behavior you are seeing.

**Comment by westes** [comment]
That could be it. I will install from git just before this change, then.

**Comment by DemiMarie** [comment]
I just pushed a commit that should fix it.

**Comment by westes** [comment]
Yes, that helped too. And so did installing from a more recent version. It's on master and will go in 2.6.2.

**Pull request closed without merging**
