### PR TITLE
Changes and Edits in the README File

### PR DESCRIPTION
**Pull request by Lin-Selina**
-Edited the README file documentation
-No code edited
-Kept the original content
-Added in more structure and additional information to help users who would like to use this project

### CODE REVIEW

**Comment by westes** [comment]
according to github, the TOC should show up automagically.

**Comment by westes** [comment]
I'm not sure that I think of thise document as a web-first document, so the links to files aren't really a thing I've worried about.

**Comment by westes** [comment]
It's not clear how the explanation of scanners and flex helps people who know they need to use flex.

**Comment by Mightyjo** [comment]
Retracting my statement that this deletes some original content. With one exception: "This is flex, the fast lexical analyzer generator." It's iconic and should remain intact.  I see where the explanation of the repository structure ended up, now.

I don't think linking to top level files and directories from README.md is useful. Particularly since GitHub added the repo navigator bar to the left side of the screen.

I don't love this explanation of scanner applications. It conflates the roles of scanners and parsers in its examples. That's already confusing enough for new folks without us throwing murky water in the mix. I'd rather say nothing or point newcomers to a good book.

**Comment by westes** [comment]
As noted in the comments, this pull request has multiple problems. This pull request does not address any current needs of the flex project. As such, I am closing this pull request.

**Pull request closed without merging**
