### PR TITLE
change token name 'CHAR' to 'TOK_CHAR'

### PR DESCRIPTION
**Pull request by jannick0**
change avoids conflict with type definition of CHAR

### CODE REVIEW

**Comment by Explorer09** [comment]
What's anything wrong with the type definition of CHAR?

**Comment by Explorer09** [comment]
What's anything wrong with the type definition of CHAR? It's a Flex internal symbol, and not available in generated scanners. Where's the necessity of renaming?

**Comment by jannick0** [comment]
For now there is no conflict with the definition of `CHAR` in Windows' system header `winnt.h`. This change does not harm the flex code at all.

**Comment by Explorer09** [comment]
@jannick0 
I would bring inconsistency in Flex tokens' naming. If it doesn't break, don't fix it.
I personally would suggest prefixing all Flex tokens with FLEX_TOK_ if we are to address name conflict problems in the future.

**Comment by jannick0** [comment]
The `TOK_` prefix is already used in flex' bison grammar, so no additional inconsistency. Separately, I would agree to the longer version of a fully consistent prefix, however I would be concerned to make the bison grammar less readable then once the longer token names are used therein (given that that we cannot - or rather must not - expect a minimum version of bison for compiling flex.)

**Comment by westes** [comment]
Yes, if we're going to indicate that something is a flex-centric thing, then we should use FLEX_ as the prefix.

On Tuesday, 26 December 2017,  9:28 am +0000, jannick0 <notifications@github.com> wrote:

> The `TOK_` prefix is already used in flex' bison grammar, so no additional inconsistency. Separately, I would agree to the longer version of a fully consistent prefix, however I would be concerned to make the bison grammar less readable then once the longer token names are used therein (given that that we cannot - or rather must not - expect a minimum version of bison for compiling flex.)
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/297#issuecomment-353945195

-- 
Will Estes
westes575@gmail.com

**Comment by jannick0** [comment]
@westes Will, would you be happy to assume `bison >= 3.0` - with a predefined bison exit status otherwise? That would help using the bison feature to consistently use a token name prefix (here: `FLEX_TOK_`) without cluttering the bison grammar itself?

**Comment by westes** [comment]
Yes.

On Tuesday, 26 December 2017,  8:57 am -0800, jannick0 <notifications@github.com> wrote:

> @westes Will, would you be happy to assume `bison >= 3.0` - with a predefined bison exit status otherwise? That would help using the bison feature to consistently use a token name prefix (here: `FLEX_TOK_`) without cluttering the bison grammar itself?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/297#issuecomment-353989446

-- 
Will Estes
westes575@gmail.com

**Comment by Explorer09** [comment]
I would prefer not to do it, since tracing all uses of the symbol would become difficult, and `find | xargs grep` would not find all the use of it.

Can we go back to the start and think of the purpose of this change? We use the prefix mainly to avoid name collision with other parts of the code, and potential collisions with user code, if they incorporate or embed Flex code to make a scanner _generator_ for their use.

The use of a unified prefix would also allow Flex symbols to stand unique in the Google search results, although this is only a side benefit.

I know you would concern about `FLEX_TOK_` being too long for a token prefix. But in this case there are alternatives. `_FLT_` could also work if we could claim the prefix for our exclusive use.

I think this issue can be deferred to the next Flex major release; existing code hasn't broke; so there is no need to rush. I can wait for more suggestions to come in before the maintainer makes a decision.

**Comment by westes** [comment]
I'm fine with FLEX_TOK_ for the flex token stuff.

I would think you'd want to use ctags or similar to find all the occurences of a token, not find.

On Tuesday, 26 December 2017,  6:00 pm +0000, "Kang-Che Sung (宋岡哲)" <notifications@github.com> wrote:

> I would prefer not to do it, since tracing all uses of the symbol would become difficult, and `find | xargs grep` would not find all the use of it.
> 
> Can we go back to the start and think of the purpose of this change? We use the prefix mainly to avoid name collision with other parts of the code, and potential collisions with user code, if they incorporate or embed Flex code to make a scanner _generator_ for their use.
> 
> The use of a unified prefix would also allow Flex symbols to stand unique in the Google search results, although this is only a side benefit.
> 
> I know you would concern about `FLEX_TOK_` being too long for a token prefix. But in this case there are alternatives. `_FLT_` could also work if we could claim the prefix for our exclusive use.
> 
> I think this issue can be deferred to the next Flex major release; existing code hasn't broke; so there is no need to rush. I can wait for more suggestions to come in before the maintainer makes a decision.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/westes/flex/pull/297#issuecomment-353995460

-- 
Will Estes
westes575@gmail.com

**Comment by jannick0** [comment]
Replaced by #299.

**Pull request closed without merging**
