### PR TITLE
test: use portable pattern substitution in tableopts.sh

### PR DESCRIPTION
**Pull request by Explorer09**
Fixes: #222

### CODE REVIEW

**Comment by westes** [comment]
@0-wiz-0, can you confirm that this works on NetBSD?

**Comment by westes** [comment]
The test suite builds and runs under linux (aka my laptop).

**Comment by 0-wiz-0** [comment]
Yes, the patch fixes the problem. Thanks, @Explorer09 !

**Comment by westes** [comment]
This is now on master. Much thanks.

**Pull request merged**
